name: CI

on: [push]

jobs:

  activate:
    runs-on: self-ubuntu-20.04
    if: |
      github.repository == 'feelpp/school.swimming.2021' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  latex: 
    if: "!contains(github.event.head_commit.message, 'doc skip')"
    needs: activate
    runs-on: self-ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2   
      - name: Compile LaTeX document
        run: |
          pdflatex --shell-escape course.tex
          bibtex course
          pdflatex --shell-escape course.tex
          pdflatex --shell-escape course.tex
        working-directory: course
      - name: move pdf
        run: |
          mv course/course.pdf modules/ROOT/attachments/inria-school-2021-course-math-comp-swimming-framework.pdf
      - name: commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          date=$(date +%Y-%m-%d)
          git add modules/ROOT/attachments/inria-school-2021-course-math-comp-swimming-framework.pdf
          git commit -m "Auto updating of inria school course "${date}""
          git push

  antora:
    if: "!contains(github.event.head_commit.message, 'doc skip')"
    needs: latex
    runs-on: self-ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - name: Install credentials
      run: echo https://$GITHUB_OAUTH:@github.com > $HOME/.git-credentials
      env:
        GITHUB_OAUTH: ${{ secrets.CR_PAT }}
    - name: Build
      run: npm run antora
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.

 